### ISSUE TITLE
Help with javascript specifics (int passed by value)

### ISSUE THREAD

**Issue by vletoux** [freehuntx/frida-mono-api#8]
Thanks for sharing this code.

Maybe this is something completely stupid, but I'm unable to call a function asking for an int.
I can call every function with an object, string, etc but not this.
With an int, it ends with "invalid argument'

Example:
![image](https://user-images.githubusercontent.com/10632326/94361049-deaca580-00b1-11eb-99ed-767bec8b7a2b.png)

I managed to understand my problem as javascript pass int by value, and not by reference.
Indeed, in the c mono documentation that I read, every int is passed by reference (&i)

If there is a trick, please be kind to add a remark on this github.
Maybe add an helper like you did with strings.

**Comment by freehuntx** [comment]
Im currently reworking "frida-mono" and it will contain everything needed to work with mono.
This repo will become obsolete when thats done.
You can follow the current state in this branch: https://github.com/freehuntx/frida-mono/tree/feature/v1

I wont concentrate on fixing things here since im not happy with the codebase.
Keep an eye on frida-mono :)

**Comment by vletoux** [comment]
Thanks for your excellent work on this
